### ISSUE TITLE
Use typescript

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-core#127]
Since this library supports different database types and all of them need to follow the same interface contract it would be simpler to ensure those contracts are being respected if it was written in typescript.

**Comment by MasterOdin** [comment]
This has been accomplished with https://github.com/sqlectron/sqlectron-gui/commit/5083dedec2cc9826d073f59fda31cc4923759486 at the same time as merging this repo into the gui to ease development efforts. This repo is being archived as a result, and so will not see a new version with typescript.
