### ISSUE TITLE
Fetching table columns (and triggers)

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-core#13]
Although this is change in GUI too, I think its better to keep this issue here. As mentioned [earlier](https://github.com/sqlectron/sqlectron-gui/issues/98) ,now that we have database metadata menu, there should be (at least) list of columns for each table, so that user does not have to do manual query to check existing columns. Furthermore, If there will be auto complete feature, fetching table columns would be required anyways. 

If you agree with a idea, I plan on working on this in a week to come, so @maxcnunes you can expect PR on this soon.

**Comment by maxcnunes** [comment]
Sure. Go for it :+1:

**Comment by maxcnunes** [comment]
Closing it since have been merged and published on NPM.
By the way, awesome pull request 👏
