### ISSUE TITLE
PostgreSQL SSL Support

### ISSUE THREAD

**Issue by ckee83** [sqlectron/sqlectron-core#16]
Following up on the [sqlectron-gui issue to add SSL mode](https://github.com/sqlectron/sqlectron-gui/issues/72), I found I was still unable to connect to my Heroku psql db. 

![sqlectron-ssl](https://cloud.githubusercontent.com/assets/10836417/15095272/44e71ff4-1473-11e6-818f-11d5cfd33fea.jpg)

Note that error states SSL is off, despite state of "SSL Mode" switch.  Digging into the code, I found the problem was with sqlectron-core. While MySQL and SQLServer both adopt ssl settings from server.config, PostgreSQL does not. 

I am submitting a pull request with the fix, and while I have built sqlectron-gui and tested that it does in fact work, I did not write specs as there were none for the already implemented mysql and sqlserver ssl support.

**Comment by maxcnunes** [comment]
Good catch. Thanks @ckee83 👏 👏 👏
