### ISSUE TITLE
Support for SQL Server Schemas other than dbo

### ISSUE THREAD

**Issue by micahparker** [sqlectron/sqlectron-core#28]
The table list comes through just fine only its devoid of schema names so all of the snippets are incorrectly generated. Also there is no way to get a list of Schemas so one would have to know before hand the schema names of the tables in question.

Id be happy to jump in and develop this support if you are willing...

**Comment by maxcnunes** [comment]
Yeah, a pull request for that would be awesome :smile:

**Comment by eMerzh** [comment]
Hi... I've added listschema support for postgresql and msSQL (#29). I'm now working towards adding support to other methods like table listing,... But I have no knowledge of msSQL and no access to one. So it might be a chance to give a hand :)

**Comment by eMerzh** [comment]
now that #30 is merged, the basis for schema support are there... we only need to adapt them to sqlserver

**Comment by micahparker** [comment]
Sorry ive been MIA, work picked up unexpectedly... i hope to look at this soon
