### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by cswarth** [sqlectron/sqlectron-core#34]
New to Node so I'm sure I'm missing something really basic.
`npm install sqlectron-core` fails for me.

Using `Node 6.8.1` installed via `brew` on MacOS Sierra 10.12 (16A323)
```
$ npm --version
3.10.8

$ npm install sqlectron-core
/Users/cswarth
└─┬ sqlectron-core@7.0.0 
  └── pg@4.5.5  (git+https://github.com/maxcnunes/node-postgres.git#7d31f4f96d5e5ee94260ca0f2aaec9957a53edb6)

npm WARN enoent ENOENT: no such file or directory, open '/Users/cswarth/package.json'
npm WARN cswarth No description
npm WARN cswarth No repository field.
npm WARN cswarth No README data
npm WARN cswarth No license field.
```

**Comment by cswarth** [comment]
I haven't been able to complete the workaround yet, but I suspect this has to do with installing `node` via homebrew.

Fixing npm On Mac OS X for Homebrew Users
https://gist.github.com/DanHerbert/9520689

**Comment by maxcnunes** [comment]
Try install node with [nvm](https://github.com/creationix/nvm). I have been using it with node 6.5.0 and it is working properly.
