### ISSUE TITLE
Product Name

### ISSUE THREAD

**Issue by codeandcats** [sqlectron/sqlectron-core#38]
Just wanted to make a friendly suggestion. I think the current name isn't as optimal as it could be. I find it's unclear and awkward to pronounce. Is it "sequel-ectron", "s-q-l-ectron"?

Would you consider changing the name to simply... 

**_Selectron_**

It's
- Unambiguous
- Easy to pronounce
- Rhymes with the key technology you're using without even adding more syllables
- Rolls off the tongue
- Plus selectron.io is available... 😉 

Just a thought, no disrespect intended 🌹

**Comment by maxcnunes** [comment]
Hi @codeandcats,

Thanks for the suggestion. The way I pronounce it is "sequelectron" - https://translate.google.com/?source=osdd#en/en/sequelectron. I don't think is that harder this way. Although you have good reasons to change the name. I still prefer the sound of "sequelectron" than "selectron" :)
I will include a session in the docs explaining how pronounce it. Which should make clear right away for new users.

Again, thanks for your feedback :)
