### ISSUE TITLE
.sqlectron.json passwords security

### ISSUE THREAD

**Issue by volym3ad** [sqlectron/sqlectron-core#39]
Why passwords are stored inside .sqlectron.json in open format?
Why do not use simple hashing at least?

**Comment by maxcnunes** [comment]
The initial idea was using this approach https://github.com/sqlectron/sqlectron-gui/issues/168.
Which would save passwords in the system's keychain. But we never had time to implement that.
I agree simple hashing is better than plain text. So I will improve that.

**Comment by volym3ad** [comment]
Nice. This will be great =)

**Comment by araujoigor** [comment]
I proposed a possible simple/temporary solution for this on #42. Please take a look and see what you guys think.

**Comment by maxcnunes** [comment]
Closed by #43
