### ISSUE TITLE
docker-compose up doesn't work

### ISSUE THREAD

**Issue by luisrudge** [sqlectron/sqlectron-core#4]
![image](https://cloud.githubusercontent.com/assets/941075/11642250/040295de-9d24-11e5-8a25-9a47e57d2ab0.png)

**Comment by maxcnunes** [comment]
It is working normally here with the docker `v1.7.1` and docker-compose `v1.4.2` running on OSX + Vagrant (vmware).

We usually don't use `docker-compose up` for tests. Could you try running it with `docker-compose run --rm test` (I have update the [docs](https://github.com/sqlectron/sqlectron-core#with-docker--docker-compose))?

Although I don't think this is the problem. Maybe could be a problem between the boot2docker and the docker mapping the volume from your machine to the container.

**Comment by luisrudge** [comment]
![image](https://cloud.githubusercontent.com/assets/941075/11642991/4995b26c-9d28-11e5-995b-62ebd1f810aa.png)

Damnnnnnnnnnnnnn :(

**Comment by luisrudge** [comment]
![image](https://cloud.githubusercontent.com/assets/941075/11643044/9a22b13a-9d28-11e5-944a-1ba066da8eff.png)

**Comment by maxcnunes** [comment]
Humm I don't think the versions of docker and compose could cause this problem. Seems more like a volume problem between boot2docker and the docker container.

Could you try change the volume path and use this [approach](https://github.com/docker/compose/issues/26#issuecomment-59468702)?
And I think you will need use a shared folder - [docs](https://github.com/boot2docker/boot2docker#folder-sharing).
Maybe [this](http://stackoverflow.com/a/29901502/1050818) can help too.

**Comment by maxcnunes** [comment]
Since this isn't a problem with the sqlectron. But with docker + volumes on windows. I will close it for now.
