### ISSUE TITLE
MySQL bit type

### ISSUE THREAD

**Issue by pietrocaselani** [sqlectron/sqlectron-core#40]
Bit types values in MySQL databases are shown as `"{""type"":""Buffer"",""data"":[0]}"` or `"{""type"":""Buffer"",""data"":[1]}"` instead of `0` or `1`.
I don't know if this behavior occurs only on MySQL.

**Comment by maxcnunes** [comment]
Are you using this module elsewhere besides sqlectron-gui? I have fixed that on sqlectron-gui with this commit https://github.com/sqlectron/sqlectron-gui/commit/ba2550e29814e6766fcbf4f1acf91d0307d9d89b. And that was released on version [1.20.1](https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.20.1).

**Comment by pietrocaselani** [comment]
oh.. sorry, I was using version 1.19.0!
