### ISSUE TITLE
Follow operating system config location standards

### ISSUE THREAD

**Issue by Siilwyn** [sqlectron/sqlectron-core#46]
It would be great if this module followed the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Instead of placing the configuration file in the home directory it should be placed in the appropriate directory. Getting the correct directory is easy with a module like [env-paths](https://github.com/sindresorhus/env-paths). This, among other things, allows a user to specify a directory in which they want all applications to look for their user configurable setting files and keep their home directory clean.

**Comment by maxcnunes** [comment]
This issue already exists on https://github.com/sqlectron/sqlectron-gui/issues/327. But nobody couldn't work on that yet. I may have some free time this weekend. Lets see 🤞

**Comment by Siilwyn** [comment]
Whoops didn't see that one, I assume the implementation is in core since the CLI has the same behaviour right?
Either way your reply there sounds good! The only thing I would advice is to use the `env-paths` module to handle getting the correct path. I've migrated the cache and/or data location of a few modules so far and using this module simplifies the implementation a lot.

**Comment by Siilwyn** [comment]
Oh wow that was blazing fast! ⚡️ Much appreciated!
