### ISSUE TITLE
add appveyor

### ISSUE THREAD

**Issue by luisrudge** [sqlectron/sqlectron-core#5]
@maxcnunes can you look at those errors, please? https://ci.appveyor.com/project/luisrudge/sqlectron-core
 It's on my username now so I don't flood your repo with changes. once it's working I'll open a PR

**Comment by luisrudge** [comment]
ok, I fixed :D opening the PR in a few mins

**Comment by maxcnunes** [comment]
The tests are breaking with Docker. Thats why the MySQL does not contains the tables `mysql` and `performance_schema`. You are using the mysql `5.6` for tests on AppVeyor and the Docker is using the version `5.7`. I will try find out tomorrow the reason of this difference. If you have any idea, please let me know.

**Comment by luisrudge** [comment]
Sorry! I can't run docker tests here :( I'll build an ubuntu vm to run docker tomorrow. I asked appveyor to add support for mongo 5.7, then we'll be good!
