### ISSUE TITLE
Provide ability to configure the location of the config JSON

### ISSUE THREAD

**Issue by jrgleason** [sqlectron/sqlectron-core#50]
At work they blow away our user folder every night so I need to configure the location of the config file. I don't see anything in the docs that suggest this is supported.

I would like to store my config in a location other than `\AppData\Local\Sqlectron\Config`

**Comment by mblarsen** [comment]
I'd like to have one per project basis. E.g if `.sqlectron.json` exist in the current directory it will read that.

**Comment by MasterOdin** [comment]
Done in #116
